### ISSUE TITLE
Action version resolution never works

### ISSUE THREAD

**Issue by rdunnington** [jcbhmr/setup-wasm-tools#1]
Hi,

I would really like to use this action but it seems like it always fails no matter what version I specify, or even if I leave it to be the default:

```
node:internal/per_context/domexception:53
    ErrorCaptureStackTrace(this);
    ^
Error: ption [Error]: 1.207 resolved to null
    at new DOMException (node:internal/per_context/domexception:53:5)
    at file:///D:/a/_actions/jcbhmr/setup-wasm-tools/v2/dist/main.js:27422:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

https://github.com/rdunnington/bytebox/actions/runs/9142457688/job/25138027232#step:7:16

I'm using it like this:
```yml
      - name: Setup wasm-tools 
        uses: jcbhmr/setup-wasm-tools@v2
        with:
          wasm-tools-version: 1.207
```

https://github.com/rdunnington/bytebox/pull/37/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR42-R45

I'm not the most experienced GitHub actions user so I could be doing something wrong, feel free to let me know. Thanks!
